name: wizard_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^4.0.4
  cached_network_image: ^3.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true
  fonts:
    - family: HarryP
      fonts:
        - asset: fonts/HarryP-MVZ6w.ttf

